if(location.hostname!="websites.cobalt.com"){var errorFn=function(oError){var errorFn=function(oError){if(oError.target.src.indexOf("blue.thelivechatsoftware.com/signalrserver/Scripts/jquery.signalR")>-1){SRerror=true;WGWindowLoader.loadGVarsFiles()}};};if(window.WGWindowLoader)
throw new Error("Window already loaded");var urlHost=location.hostname.toString(),urlHost=urlHost.match(/^www\./)?urlHost.substring(4):location.hostname.toString();var SRerror=false;var WGWindowLoader={chat:null,randomnumber:Math.floor(Math.random()*11),LC_SN:"LC_SN",live_chat_Image:null,disabled:false,signalRConnected:false,strofLibrary:"strophe",jqueryForChat:"jqueryforchat",jqueryUIForChat:"jqueryuiforchat-la",gvarsLibrary:"gvars",chatWindowLibrary:"LAchatwindow",chatScriptLibrary:"jqchatscriptyui",chatScriptLibraryNOSR:"jqyuinosrnoconflict",vb:"vb",codesVersion:"?v=16",jqueryLoading:false,protocol:window.location.protocol+"//",keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",cdn:"cdn.thelivechatsoftware.com/scripts/",MsgWin:document.getElementById("txtMessageWin"),ChatWin:document.getElementById("txtChatWin"),CallSignalR:function(){if(WGWindowLoader.signalRConnected)
if(WGWindowLoader.laJquery.connection.hub&&WGWindowLoader.laJquery.connection.hub.state===WGWindowLoader.laJquery.signalR.connectionState.connected){WGWindowLoader.chat.server.inviteOperator(laScriptObj.chatId,laScriptObj.visitorId,laScriptObj.visitorName,laScriptObj.actualUserId);document.getElementById("txtMessageWin").onkeyup=function(e){if(e.keyCode==32&&laScriptObj.isAlreadyInChat)
WGWindowLoader.chat.server.invokeMessage(laScriptObj.chatId,WGWindowLoader.laJquery("#txtMessageWin").val(),"visitor");if(e.keyCode==13&&laScriptObj.isAlreadyInChat)
WGWindowLoader.chat.server.invokeMessage(laScriptObj.chatId," ","visitor");if(e.keyCode==8&&laScriptObj.isAlreadyInChat)
WGWindowLoader.chat.server.invokeMessage(laScriptObj.chatId," ","visitor")}}},WGEncode:function(input){var output="";var chr1,chr2,chr3;var enc1,enc2,enc3,enc4;var i=0;do{chr1=input.charCodeAt(i++);chr2=input.charCodeAt(i++);chr3=input.charCodeAt(i++);enc1=chr1>>2;enc2=(chr1&3)<<4|chr2>>4;enc3=(chr2&15)<<2|chr3>>6;enc4=chr3&63;if(isNaN(chr2))
enc3=enc4=64;else if(isNaN(chr3))
enc4=64;output=output+WGWindowLoader.keyStr.charAt(enc1)+WGWindowLoader.keyStr.charAt(enc2)+WGWindowLoader.keyStr.charAt(enc3)+WGWindowLoader.keyStr.charAt(enc4)}while(i<input.length);return output},getRandomValue:function(){var dt=new Date;return dt.getTime().toString()},getDomainName:function(referrer){if(laScriptObj.referrer)
return laScriptObj.referrer.split(/\/+/g)[1];else
return""},ReplaceSpecialCharacters:function(stringValue){var updatedString="";updatedString=stringValue.replace(/#/g,"%23");updatedString=updatedString.replace(/&/g,"%26");return updatedString},getReferrer:function(){var ref="";if(document.referrer&&document.referrer!="")
ref=laScriptObj.ReplaceSpecialCharacters(document.referrer.toString());return ref},parseURL:function(url){remaining_url=url.substr(0,url.length);domain_i=remaining_url.indexOf("/");domain_i=domain_i==-1?remaining_url.length:domain_i;var domain=remaining_url.substr(0,domain_i);return domain},createCookie:function(cookieName,value,hours){if(hours){var date=new Date;date.setTime(date.getTime()+hours*60*60*1E3);var expires="; expires="+date.toGMTString()}else
var expires="";document.cookie=cookieName+"="+value+expires+"; path=/; domain="+laScriptObj.parseURL(laScriptObj.host)+";"},readCookie:function(name){var nameEQ=name+"=";var ca=document.cookie.split(";");for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==" ")
c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)
return c.substring(nameEQ.length,c.length)}},readCookieJson:function(name){var returnData="";var nameEQ=name+"=";var ca=document.cookie.split(";");for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==" ")
c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)
returnData=c.substring(nameEQ.length,c.length)}
if(returnData!="")
return eval("("+returnData+")");else
return""},WGDecode:function(input){var output="";var chr1,chr2,chr3;var enc1,enc2,enc3,enc4;var i=0;input=input.replace(/[^A-Za-z0-9\+\/=]/g,"");do{enc1=WGWindowLoader.keyStr.indexOf(input.charAt(i++));enc2=WGWindowLoader.keyStr.indexOf(input.charAt(i++));enc3=WGWindowLoader.keyStr.indexOf(input.charAt(i++));enc4=WGWindowLoader.keyStr.indexOf(input.charAt(i++));chr1=enc1<<2|enc2>>4;chr2=(enc2&15)<<4|enc3>>2;chr3=(enc3&3)<<6|enc4;output=output+String.fromCharCode(chr1);if(enc3!=64)
output=output+String.fromCharCode(chr2);if(enc4!=64)
output=output+String.fromCharCode(chr3)}while(i<input.length);return output},loadFile:function(filename,fileType,where){var fileRef;if(fileType=="js"){fileRef=document.createElement("script");fileRef.setAttribute("type","text/javascript");fileRef.setAttribute("src",filename);fileRef.async=true}else if(fileType=="css"){fileRef=document.createElement("link");fileRef.setAttribute("rel","stylesheet");fileRef.setAttribute("type","text/css");fileRef.setAttribute("href",filename)}
if(typeof fileRef!="undefined")
if(where=="head")
document.getElementsByTagName("head")[0].appendChild(fileRef);else
document.getElementsByTagName("body")[0].appendChild(fileRef)},loadScripts:function(){if(WGWindowLoader.disabled)
return false;if(typeof jQuery!="function"||false){WGWindowLoader.jqueryLoading=true;WGWindowLoader.loadFile(WGWindowLoader.protocol+WGWindowLoader.cdn+"JQuery/jquery-1.11.2.js","js","head")}
loaderLib.loadLibraries(WGWindowLoader.strofLibrary)},encode64:function(input){WGWindowLoader.keyStr="ABCDEFGHIJKLMNOP"+"QRSTUVWXYZabcdef"+"ghijklmnopqrstuv"+"wxyz0123456789+/"+"=";input=escape(input);var output="";var chr1,chr2,chr3="";var enc1,enc2,enc3,enc4="";var i=0;do{chr1=input.charCodeAt(i++);chr2=input.charCodeAt(i++);chr3=input.charCodeAt(i++);enc1=chr1>>2;enc2=(chr1&3)<<4|chr2>>4;enc3=(chr2&15)<<2|chr3>>6;enc4=chr3&63;if(isNaN(chr2))
enc3=enc4=64;else if(isNaN(chr3))
enc4=64;output=output+WGWindowLoader.keyStr.charAt(enc1)+WGWindowLoader.keyStr.charAt(enc2)+WGWindowLoader.keyStr.charAt(enc3)+WGWindowLoader.keyStr.charAt(enc4);chr1=chr2=chr3="";enc1=enc2=enc3=enc4=""}while(i<input.length);return output},loadScriptDynamic:function(url,where,callback){if(typeof require!="undefined"&&typeof requirejs!="undefined")
require([url],function(){callback()});else{var script=document.createElement("script");script.type="text/javascript";if(script.readyState)
script.onreadystatechange=function(){if(script.readyState=="loaded"||script.readyState=="complete"){script.onreadystatechange=null;callback()}};else
script.onload=function(){callback()};script.onerror=errorFn;script.src=url;if(typeof url!="undefined")
if(where=="head")
document.getElementsByTagName("head")[0].appendChild(script);else
document.getElementsByTagName("body")[0].appendChild(script)}
if(typeof require!="undefined"&&typeof requirejs!="undefined")
requirejs.onError=function(err){if(err.requireType==="timeout"||err.requireType==="scripterror");}},loadJQueryFiles:function(){WGWindowLoader.loadScriptDynamic(WGWindowLoader.protocol+WGWindowLoader.cdn+"JQuery/"+WGWindowLoader.jqueryForChat+".js"+WGWindowLoader.codesVersion,"head",function(){WGWindowLoader.laJquery=jQuery.noConflict(true);WGWindowLoader.laJquery.easing.jswing=true;WGWindowLoader.loadJQueryUIFiles()})},loadJQueryUIFiles:function(){WGWindowLoader.loadScriptDynamic(WGWindowLoader.protocol+WGWindowLoader.cdn+"JQuery/"+WGWindowLoader.jqueryUIForChat+".js"+WGWindowLoader.codesVersion,"head",function(){WGWindowLoader.loadSignalRFilesJquery()})},loadStrophFiles:function(){WGWindowLoader.loadScriptDynamic(WGWindowLoader.protocol+
WGWindowLoader.cdn+"JQuery/"+WGWindowLoader.strofLibrary+".js"+WGWindowLoader.codesVersion,"head",function(){if(typeof jQuery!="function"&&window.JSON)
WGWindowLoader.loadJQueryFiles();else if(typeof jQuery=="function"&&window.JSON)
WGWindowLoader.loadJQueryFiles();else{SRerror=true;WGWindowLoader.loadGVarsFiles()}})},loadSignalRFilesJquery:function(){WGWindowLoader.loadScriptDynamic(WGWindowLoader.protocol+"blue.thelivechatsoftware.com/signalrserver/Scripts/jquery.signalR-2.1.2.min-la.js"+WGWindowLoader.codesVersion,"head",function(){WGWindowLoader.loadSignalRFilesHub()})},loadSignalRFilesHub:function(){WGWindowLoader.loadScriptDynamic(WGWindowLoader.protocol+"blue.thelivechatsoftware.com/signalrserver/scripts/hubssingle-la-2.js"+WGWindowLoader.codesVersion,"head",function(){WGWindowLoader.loadGVarsFiles()})},loadGVarsFiles:function(){WGWindowLoader.loadScriptDynamic(WGWindowLoader.protocol+"cdn.thelivechatsoftware.com/Company/"+WGWindowLoader.WGDecode(window.WGAccountID)+"new/"+WGWindowLoader.gvarsLibrary+".js"+WGWindowLoader.codesVersion,"head",function(){WGWindowLoader.loadVB()})},loadVB:function(){WGWindowLoader.loadScriptDynamic(WGWindowLoader.protocol+"thelivechatsoftware.com/dashboard/cwgen/Company/"+WGWindowLoader.WGDecode(window.WGAccountID)+"new/"+WGWindowLoader.vb+".js"+WGWindowLoader.codesVersion,"head",function(){WGWindowLoader.loadChatWindowFiles()})},loadChatWindowFiles:function(){WGWindowLoader.loadScriptDynamic(WGWindowLoader.protocol+"cdn.thelivechatsoftware.com/Company/"+WGWindowLoader.WGDecode(window.WGAccountID)+"new/"+
WGWindowLoader.chatWindowLibrary+".js"+WGWindowLoader.codesVersion,"body",function(){if(!SRerror){WGWindowLoader.loadChatScriptFiles();}else{WGWindowLoader.loadChatScriptNOSRFiles()}})},loadChatScriptNOSRFiles:function(){WGWindowLoader.loadScriptDynamic(WGWindowLoader.protocol+WGWindowLoader.cdn+WGWindowLoader.chatScriptLibraryNOSR+".js"+WGWindowLoader.codesVersion,"head",function(){WGWindowLoader.MsgWin=document.getElementById("txtMessageWin");WGWindowLoader.laJquery("#txtMessageWin").focus(WGWindowLoader.txtFocusing);document.getElementById("closeBTN").onclick=WGWindowLoader.sendXmppChatDestroy;WGWindowLoader.laJquery("#btnSend").click(WGChat.SendChatMessage);if(typeof WGWindowConstant.MLang!="undefined"&&WGWindowConstant.MLang){WGMLanguage.allLanguages=document.getElementById("selLang");WGWindowLoader.laJquery("#ChatDiv").append(currentLanguage);WGWindowLoader.laJquery("#ChatDiv").append(WGMLanguage.allLanguages);if(typeof WGWindowConstant.MLang!="undefined"&&WGWindowConstant.MLang&&document.getElementById("selLang")!="undefined")
document.getElementById("selLang").style.zindex="1000"}
WGWindowLoader.ChatWin=document.getElementById("txtChatWin");checkVersion();WGWindowLoader.live_chat_Image=document.getElementById("live_chat_img");if(typeof WGWindowConstant.SName!="undefined"&&WGWindowConstant.SName)
if(WGWindowLoader.readCookie(WGWindowLoader.LC_SN)!=null)
WGWindowConstant.mySName[WGWindowLoader.randomnumber]=WGWindowLoader.readCookie(WGWindowLoader.LC_SN);else
WGWindowLoader.createCookie(WGWindowLoader.LC_SN,WGWindowConstant.mySName[WGWindowLoader.randomnumber],12);WGWindowLoader.laJquery("#txtMessageWin").keypress(function(e){if(e.which==13){WGWindowLoader.onKeyPressFunc();return false}});WGWindowLoader.MainThread()})},loadChatScriptFiles:function(){WGWindowLoader.loadScriptDynamic(WGWindowLoader.protocol+WGWindowLoader.cdn+WGWindowLoader.chatScriptLibrary+".js"+WGWindowLoader.codesVersion,"head",function(){WGWindowLoader.MsgWin=document.getElementById("txtMessageWin");WGWindowLoader.laJquery("#txtMessageWin").focus(laScriptObj.txtFocusing);document.getElementById("closeBTN").onclick=laScriptObj.sendXmppChatDestroy;WGWindowLoader.laJquery("#btnSend").click(WGChat.SendChatMessage);if(typeof WGWindowConstant.MLang!="undefined"&&WGWindowConstant.MLang){WGMLanguage.allLanguages=document.getElementById("selLang");WGWindowLoader.laJquery("#ChatDiv").append(currentLanguage);WGWindowLoader.laJquery("#ChatDiv").append(WGMLanguage.allLanguages);if(typeof WGWindowConstant.MLang!="undefined"&&WGWindowConstant.MLang&&document.getElementById("selLang")!="undefined")
document.getElementById("selLang").style.zindex="1000"}
WGWindowLoader.ChatWin=document.getElementById("txtChatWin");checkVersion();WGWindowLoader.live_chat_Image=document.getElementById("live_chat_img");if(typeof WGWindowConstant.SName!="undefined"&&WGWindowConstant.SName)
if(laScriptObj.readCookie(WGWindowLoader.LC_SN)!=null)
WGWindowConstant.mySName[WGWindowLoader.randomnumber]=laScriptObj.readCookie(WGWindowLoader.LC_SN);else
laScriptObj.createCookie(WGWindowLoader.LC_SN,WGWindowConstant.mySName[WGWindowLoader.randomnumber],12);WGWindowLoader.laJquery("#txtMessageWin").keypress(function(e){if(e.which==13){laScriptObj.onKeyPressFunc();return false}});laScriptObj.MainThread()})}};WebFontConfig={google:{families:["Titillium+Web::latin"]}};WGWindowLoader.loadFile(WGWindowLoader.protocol+"cdn.thelivechatsoftware.com/Company/"+WGWindowLoader.WGDecode(window.WGAccountID)+"new/"+"LAchatwindow.css","css","head");WGWindowLoader.loadFile(window.location.protocol+"//ajax.googleapis.com/ajax/libs/webfont/1/webfont.js","js","head");WGWindowLoader.randomNumber="?i="+WGWindowLoader.getRandomValue();WGWindowLoader.loadStrophFiles()};